# Generated by Django 5.0.3 on 2024-03-23 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.IntegerField(null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_address', models.CharField(max_length=200, null=True)),
                ('customer_mobile', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(null=True)),
                ('item_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('unit_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('qty_available', models.PositiveIntegerField(default=0, null=True)),
                ('qty_sold', models.PositiveIntegerField(default=0, null=True)),
                ('qty_purchased', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('userid', models.CharField(default=uuid.uuid4, max_length=36)),
                ('regnumber', models.IntegerField(null=True)),
                ('regnumber1', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('po_no', models.IntegerField(null=True)),
                ('po_number', models.CharField(max_length=100, null=True, unique=True)),
                ('gross_amount', models.PositiveIntegerField(null=True)),
                ('discount', models.PositiveIntegerField(null=True)),
                ('net_amount', models.PositiveIntegerField(null=True)),
                ('net_pending', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_no', models.IntegerField(null=True)),
                ('vendor_id', models.CharField(max_length=100, null=True, unique=True)),
                ('vendor_name', models.CharField(max_length=100, null=True)),
                ('vendor_address', models.CharField(max_length=200, null=True)),
                ('vendor_mobile', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_no', models.IntegerField(null=True)),
                ('payment_id', models.CharField(max_length=100, null=True, unique=True)),
                ('paid', models.PositiveIntegerField(default=0, null=True)),
                ('total', models.PositiveIntegerField(null=True)),
                ('pending', models.PositiveIntegerField(default=0, null=True)),
                ('po_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('return_qty', models.PositiveIntegerField(default=0, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('po_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('so_no', models.IntegerField(null=True)),
                ('so_number', models.CharField(max_length=100, null=True, unique=True)),
                ('gross_amount', models.PositiveIntegerField(null=True)),
                ('discount', models.PositiveIntegerField(null=True)),
                ('net_amount', models.PositiveIntegerField(null=True)),
                ('net_pending', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_no', models.IntegerField(null=True)),
                ('payment_id', models.CharField(max_length=100, null=True, unique=True)),
                ('paid', models.PositiveIntegerField(default=0, null=True)),
                ('total', models.PositiveIntegerField(null=True)),
                ('pending', models.PositiveIntegerField(default=0, null=True)),
                ('so_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('return_qty', models.PositiveIntegerField(default=0, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('so_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('unit_price', models.PositiveIntegerField(default=0, null=True)),
                ('total_amt', models.PositiveIntegerField(null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('so_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.salesorder')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor'),
        ),
        migrations.CreateModel(
            name='PurchasedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('unit_price', models.PositiveIntegerField(default=0, null=True)),
                ('total_amt', models.PositiveIntegerField(null=True)),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('po_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchaseorder')),
                ('vendor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor')),
            ],
        ),
    ]
