# Generated by Django 4.1 on 2022-09-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='u_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
