# Generated by Django 4.1 on 2022-09-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
