# Generated by Django 4.1 on 2022-09-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_order_u_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='u_price',
        ),
    ]
