# Generated by Django 4.1 on 2022-09-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_order_u_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='u_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productunitprice', to='dashboard.product'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'unit_price'), name='unique_migration_host_combination'),
        ),
    ]
