# Generated by Django 4.1 on 2022-09-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_product_unique_migration_host_combination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='u_price',
        ),
    ]
