# Generated by Django 4.1 on 2022-09-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_order_u_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
