# Generated by Django 4.1 on 2022-09-16 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_product_total_price_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default=uuid.UUID('457e106b-440d-43b8-92cd-5b6c07fe0ba7'), max_length=100, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_address', models.CharField(max_length=200, null=True)),
                ('customer_mobile', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
