# Generated by Django 4.1 on 2022-09-16 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default=uuid.UUID('4ac7f79e-cabe-47aa-acc7-57f7f0a3e0df'), max_length=100, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_address', models.CharField(max_length=200, null=True)),
                ('customer_mobile', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Custom',
        ),
    ]
