# Generated by Django 4.1 on 2022-09-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_customer_delete_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
