# Generated by Django 4.1 on 2022-09-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_customer_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('vendor_name', models.CharField(max_length=100, null=True)),
                ('vendor_address', models.CharField(max_length=200, null=True)),
                ('vendor_mobile', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_mobile',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
