# Generated by Django 4.1 on 2022-09-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_vendor_alter_customer_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
