# Generated by Django 4.1 on 2022-09-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_vendor_vendor_id_alter_vendor_vendor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
