# Generated by Django 4.1.1 on 2022-09-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_product_category_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('unit_price', models.PositiveBigIntegerField(null=True)),
                ('qty_purchased', models.PositiveIntegerField(default=0, null=True)),
                ('qty_sold', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
