# Generated by Django 4.1.1 on 2022-10-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
