# Generated by Django 4.1.1 on 2022-10-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_custom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom',
        ),
    ]
