# Generated by Django 4.1.1 on 2022-10-01 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_delete_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.CharField(default=uuid.uuid4, max_length=36)),
                ('username', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
