# Generated by Django 4.1.1 on 2022-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_myuuidmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuuidmodel',
            name='regnumber',
            field=models.IntegerField(null=True),
        ),
    ]
