# Generated by Django 4.1.1 on 2022-10-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_myuuidmodel_regnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuuidmodel',
            name='regnumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
