# Generated by Django 4.1.1 on 2022-10-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_myuuidmodel_regnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuuidmodel',
            name='regnumber',
            field=models.IntegerField(null=True),
        ),
    ]
