# Generated by Django 4.1.1 on 2022-10-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_myuuidmodel_regnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuuidmodel',
            name='regnumber1',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
