# Generated by Django 4.1.1 on 2022-10-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_myuuidmodel_regnumber1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuuidmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
