# Generated by Django 4.1.1 on 2022-10-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_myuuidmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuuidmodel',
            name='regnumber',
        ),
    ]
