# Generated by Django 4.1.1 on 2022-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_myuuidmodel_regnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuuidmodel',
            name='regnumber',
            field=models.IntegerField(null=True),
        ),
    ]
