# Generated by Django 4.1.1 on 2022-10-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_myuuidmodel_regnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuuidmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='myuuidmodel',
            name='regnumber1',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
