# Generated by Django 4.1.1 on 2022-10-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_customer_cusomer_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cusomer_no',
            new_name='customer_no',
        ),
    ]
