# Generated by Django 4.1.1 on 2022-10-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_vendor_vendor_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
