# Generated by Django 4.1.1 on 2022-10-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_purchaseditems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditems',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor'),
        ),
    ]
