# Generated by Django 4.1.1 on 2022-10-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_purchaseditems_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditems',
            name='po_number',
        ),
    ]
