# Generated by Django 4.1.1 on 2022-10-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_remove_purchaseditems_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditems',
            name='po_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchaseorder'),
        ),
    ]
