# Generated by Django 4.1.1 on 2022-10-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_purchaseditems_po_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditems',
            name='description',
        ),
    ]
