# Generated by Django 4.1.1 on 2022-10-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_remove_purchaseditems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditems',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
