# Generated by Django 4.1.1 on 2022-10-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_purchaseditems_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseditems',
            old_name='item_id',
            new_name='item',
        ),
    ]
