# Generated by Django 4.1.1 on 2022-10-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_rename_item_id_purchaseditems_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseditems',
            old_name='item',
            new_name='item_id',
        ),
    ]
