# Generated by Django 4.1.1 on 2022-10-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_remove_purchaseditems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditems',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
