# Generated by Django 4.1.1 on 2022-10-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_purchaseditems_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditems',
            name='item_name',
        ),
    ]
