# Generated by Django 4.1.1 on 2022-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_purchaseorder_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditems',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
