# Generated by Django 4.1.1 on 2022-10-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_purchaseditems_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditems',
            name='total_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
