# Generated by Django 4.1.1 on 2022-10-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_purchaseditems_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditems',
            name='total_amount',
        ),
    ]
