# Generated by Django 4.1.1 on 2022-10-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_purchaseorder_po_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
