# Generated by Django 4.1.1 on 2022-10-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_number',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='generated_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
