# Generated by Django 4.1.1 on 2022-10-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_alter_purchaseditems_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditems',
            name='total_amt',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
