# Generated by Django 4.1.1 on 2022-10-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_alter_purchaseditems_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditems',
            name='quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseditems',
            name='total_amt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseditems',
            name='unit_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
