# Generated by Django 4.1.1 on 2022-10-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_alter_purchaseditems_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditems',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseditems',
            name='total_amt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseditems',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
