# Generated by Django 4.1.1 on 2022-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_alter_purchaseditems_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='gross_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='net_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
