# Generated by Django 4.1.1 on 2022-10-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_item_qty_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qty_available',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
