# Generated by Django 4.1.1 on 2022-10-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_item_qty_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.IntegerField(null=True)),
                ('payment_id', models.CharField(max_length=100, null=True, unique=True)),
                ('paid', models.PositiveIntegerField(null=True)),
                ('pending', models.PositiveIntegerField(null=True)),
                ('po_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchaseorder')),
            ],
        ),
    ]
