# Generated by Django 4.1.1 on 2022-10-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_payment_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
