# Generated by Django 4.1.1 on 2022-10-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_payment_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pending',
        ),
    ]
