# Generated by Django 4.1.1 on 2022-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_payment_pending_alter_payment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
