# Generated by Django 4.1.1 on 2022-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_alter_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='net_pending',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
