# Generated by Django 4.1.1 on 2022-10-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_purchaseorder_net_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='net_pending',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
