# Generated by Django 4.1.1 on 2022-10-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_remove_purchaseditems_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditems',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
