# Generated by Django 4.1.1 on 2022-10-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_remove_purchaseditems_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditems',
            name='item_id',
        ),
        migrations.AddField(
            model_name='purchaseditems',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.item'),
        ),
    ]
