# Generated by Django 4.1.1 on 2022-10-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_remove_purchaseditems_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseditems',
            old_name='item_name',
            new_name='name',
        ),
    ]
