# Generated by Django 4.1.1 on 2022-10-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_rename_item_name_purchaseditems_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseditems',
            old_name='name',
            new_name='item_name',
        ),
    ]
