# Generated by Django 4.1.1 on 2022-10-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_rename_name_purchaseditems_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor'),
        ),
    ]
