# Generated by Django 4.1.1 on 2022-10-28 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_remove_purchaseorder_vendor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('so_no', models.IntegerField(null=True)),
                ('so_number', models.CharField(max_length=100, null=True, unique=True)),
                ('gross_amount', models.PositiveIntegerField(null=True)),
                ('discount', models.PositiveIntegerField(null=True)),
                ('net_amount', models.PositiveIntegerField(null=True)),
                ('net_pending', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('unit_price', models.PositiveIntegerField(default=0, null=True)),
                ('total_amt', models.PositiveIntegerField(null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('so_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.salesorder')),
            ],
        ),
    ]
