# Generated by Django 4.1.1 on 2022-10-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_purchasereturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturn',
            old_name='item_id',
            new_name='item_name',
        ),
    ]
