# Generated by Django 4.1.1 on 2022-11-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_salesreturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesreturn',
            old_name='po_number',
            new_name='so_number',
        ),
    ]
